# Generated by Django 3.2 on 2022-05-09 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('based_on_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.day')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.CharField(choices=[('SED', 'Sedentary: little or no exercise'), ('LIT', 'Light: exercise 1-3 times/week'), ('MOD', 'Moderate: exercise 4-5 times/week'), ('ACT', 'Active: daily exercise or intense exercise 3-4 times/week'), ('VCT', 'Very Active: intense exercise 6-7 times/week'), ('ECT', 'Extra Active: very intense exercise daily, or physical job')], default='MOD', max_length=3)),
                ('goal', models.CharField(choices=[('MWL', 'Mild Weight Loss'), ('WL', 'Weight Loss'), ('EWL', 'Extreme Weight Loss'), ('MWG', 'Mild Weight Gain'), ('WG', 'Weight Gain'), ('EWG', 'Extreme Weight Gain')], default='WG', max_length=3)),
                ('program_type', models.CharField(choices=[('HOME', 'Home'), ('PPL', 'Push-Pull-Leg'), ('BSPLT', 'Bro-Split')], default='HOME', max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.programme')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workout')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.meal')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.programme')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='based_on_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.survey'),
        ),
        migrations.AddField(
            model_name='programme',
            name='meals',
            field=models.ManyToManyField(through='trainer.ProgrammeMeals', to='nutrition.Meal'),
        ),
        migrations.AddField(
            model_name='programme',
            name='workout',
            field=models.ManyToManyField(through='trainer.ProgrammeWorkouts', to='fitness.Workout'),
        ),
    ]
