# Generated by Django 3.2 on 2022-05-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='workout',
            new_name='workouts',
        ),
    ]
