# Generated by Django 3.2 on 2022-05-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_rename_workout_programme_workouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='activity',
            field=models.CharField(choices=[('SED', 'Sedentary: little or no exercise'), ('LIT', 'Light: exercise 1-3 times/week'), ('MOD', 'Moderate: exercise 4-5 times/week'), ('ACT', 'Active: daily exercise or intense exercise 3-4 times/week'), ('VCT', 'Very Active: intense exercise 6-7 times/week')], default='MOD', max_length=3),
        ),
    ]
