# Generated by Django 3.2 on 2022-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20220522_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Calories for this ingredient per 1g', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='macro',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='How much of this macro is in the ingredient per gram', max_digits=7, null=True),
        ),
    ]
