# Generated by Django 3.2 on 2022-05-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20220522_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Calories for this ingredient per 1g', max_digits=7),
        ),
        migrations.AlterField(
            model_name='macro',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='How much of this macro is in the ingredient per gram', max_digits=7),
        ),
    ]
